[project]
name = "fbreftottenhamdatascraper"
version = "0.1.0"
description = "Data Scraper for Site Fbref (Soccer Statistics)"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "bs4>=0.0.2",
    "lxml>=5.4.0",
    "numpy>=2.2.5",
    "pandas>=2.2.3",
    "requests>=2.32.3",
]
